Fix compile issue with newer version of glibc
Newer versions of glibc and gcc will detect that the open function with the O_CREAT flag requires the permissions argument be present:
Error: call to '__open_missing_mode' declared with attribute error: open with O_CREAT or O_TMPFILE in second argument needs 3 arguments